version: '3.7'

networks:
    urlshortener:
        driver: ${NETWORKS_DRIVER}

services:

    redis:
        container_name: urlshortener_redis
        image: redis:alpine
        restart: unless-stopped
        networks:
            - urlshortener

    php-server:
        container_name: urlshortener_php
        image: php
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./devops/php/Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
                - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
                - APP_GROUP=${APP_GROUP}
                - APP_GROUP_ID=${APP_GROUP_ID}
                - APP_USER=${APP_USER}
                - APP_USER_ID=${APP_USER_ID}
                - SERVICE_NAME=php
                - TZ=${TIMEZONE}
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        depends_on:
            - redis
            - mysql
        networks:
            - urlshortener

    mysql:
        container_name: urlshortener_mysql
        image: mysql:8.0
        restart: unless-stopped
        tty: true
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql:/var/lib/mysql
            - ./devops/mysql/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - urlshortener

    nginx:
        container_name: urlshortener_nginx
        image: nginx
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./devops/nginx/Dockerfile
            args:
                - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
                - APP_GROUP=${APP_GROUP}
                - APP_GROUP_ID=${APP_GROUP_ID}
                - APP_USER=${APP_USER}
                - APP_USER_ID=${APP_USER_ID}
                - CONF_FILE=${COMPOSE_PROJECT_NAME}
                - SERVICE_NAME=nginx
                - TZ=${TIMEZONE}
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-server
            - redis
            - mysql
        networks:
            urlshortener:
                aliases:
                    - ${APP_HOST}
